FROM nginx:alpine

WORKDIR /app

COPY . .

RUN chmod og+x /app

# Overwrite the NGINX configuration with the config in the project
RUN mv default.conf /etc/nginx/conf.d

EXPOSE 8080

ENTRYPOINT ["nginx", "-g", "daemon off;"]
