FROM nginx:alpine

WORKDIR /app

COPY . .

# Update file permissions to be accessible by NGINX user
RUN chmod og+x /app

# Overwrite the NGINX configuration with the config in the project
RUN mv default.conf /etc/nginx/conf.d

EXPOSE 8080

ENTRYPOINT ["nginx", "-g", "daemon off;"]
