on:
  workflow_call:
    inputs:
      configuration:
        required: true
        type: string
      artifactName:
        required: true
        type: string

env:
  DOTNET_VERSION: "8.0.x"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: "Set up .NET Core"
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: "Package Web API"
        run: dotnet build src/Serverless/OrderProcessor -c ${{ inputs.configuration }} -o ${{ env.DOTNET_ROOT }}/dist/app

      - name: "Copy Build Output"
        run: |
          mkdir -p artifact/app
          cp -R ${{ env.DOTNET_ROOT }}/dist/app/** artifact/app 
          cp src/Serverless/OrderProcessor/Dockerfile.deploy artifact/Dockerfile

      - name: "Upload Build Artifacts"
        uses: actions/upload-artifact@v4
        with:
          path: artifact
          name: ${{ inputs.artifactName }}
