FROM python:3.9-slim-buster

ARG ENTRY_POINT="function"
ARG SIGNATURE_TYPE="http"

WORKDIR /app

COPY requirements.txt .

RUN pip3 install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8080

ENTRYPOINT ["functions-framework", "--target", "$ENTRY_POINT", "--signature-type", "$FUNCTION_TYPE"]
