FROM python:3.9-slim-buster

WORKDIR /app

COPY requirements.txt .

RUN pip3 install --no-cache-dir -r requirements.txt

COPY . .

ENV ENTRY_POINT="function"
ENV SIGNATURE_TYPE="http"

EXPOSE 8080

ENTRYPOINT functions-framework --target ${ENTRY_POINT} --signature-type ${SIGNATURE_TYPE}
