name: Build & Deploy Batch Processing Web UI

on:
  push:
    branches:
      - main
      - 'release/**'
      - development
    paths:
      - 'src/BatchProcessing.Web/**'
  workflow_dispatch:

jobs:
  # Setup variables for use by subsequent jobs
  setup-env:
    name: Setup Environment Variables
    runs-on: ubuntu-latest
    outputs:
      webui-config: ${{ github.ref == 'refs/heads/main' && '' || 'development' }}
      environment: ${{ github.ref == 'refs/heads/main' && '["Demo", "Production"]' || startsWith(github.ref, 'refs/heads/release') && '["Test"]' || '["Development"]' }}
      artifactName: 'batch-processing-web'
    steps:
      - name: Empty Step
        run: |
          echo "null"

  build:
    name: Build Batch Processing Web UI
    needs: [setup-env]
    uses: ./.github/workflows/_batchprocessing.web.ci.yml
    with:
      webui-configuration: ${{ needs.setup-env.outputs.webui-config }}
      artifactName: ${{ needs.setup-env.outputs.artifactName }}
    secrets: inherit

  deploy:
    name: Deploy Batch Processing Web UI
    needs: [setup-env, build]
    uses: ./.github/workflows/_cloudrun.gcp.cd.yml
    permissions:
      id-token: write
      contents: read
    strategy:
      max-parallel: 1
      matrix:
        environment: ${{ fromJSON(needs.setup-env.outputs.environment )}}
    with:
      environment: ${{ matrix.environment }}
      ref: ${{ github.sha }}
      artifactName: ${{ needs.setup-env.outputs.artifactName }}
      serviceName: batch-processing-web
    secrets: inherit
