name: Build & Deploy Batch Processing API

on:
  push:
    branches:
      - main
      - 'release/**'
      - development
    paths:
      - 'src/BatchProcessingApi/**'
      - 'src/BatchProcessing.Models/**'
  workflow_dispatch:

jobs:
  # Setup variables for use by subsequent jobs
  setup-env:
    name: Setup Environment Variables
    runs-on: ubuntu-latest
    outputs:
      configuration: ${{ github.ref == 'refs/heads/main' && 'Release' || 'Debug' }}
      webui-config: ${{ github.ref == 'refs/heads/main' && '' || 'development' }}
      environment: ${{ github.ref == 'refs/heads/main' && '["Demo", "Production"]' || startsWith(github.ref, 'refs/heads/release') && '["Test"]' || '["Development"]' }}
      artifactName: 'batch-processing-api'
    steps:
      - name: Empty Step
        run: |
          echo "null"

  build:
    name: Build Batch Processing API
    needs: [setup-env]
    uses: ./.github/workflows/_batchprocessing.api.ci.yml
    with:
      configuration: ${{ needs.setup-env.outputs.configuration }}
      artifactName: ${{ needs.setup-env.outputs.artifactName }}
    secrets: inherit

  deploy:
    name: Deploy Batch Processing API
    needs: [setup-env, build]
    uses: ./.github/workflows/_cloudrun.gcp.cd.yml
    permissions:
      id-token: write
      contents: read
    strategy:
      matrix:
        environment: ${{ fromJSON(needs.setup-env.outputs.environment )}}
    with:
      environment: ${{ matrix.environment }}
      ref: ${{ github.sha }}
      artifactName: ${{ needs.setup-env.outputs.artifactName }}
      serviceName: batch-processing-api
      cloudRunEnvVars: '["ASPNETCORE_ENVIRONMENT=${{ matrix.environment }}"]'
    secrets: inherit
