name: Build & Deploy Batch Processing API

on:
  push:
    branches:
      - main
      - 'release/**'
      - development
    paths:
      - 'src/BatchProcessingApi/**'
      - 'src/BatchProcessing.Web/**'
      - 'src/BatchProcessing.Models/**'
  workflow_dispatch:

jobs:
  # Setup variables for use by subsequent jobs
  setup-env:
    name: Setup Environment Variables
    runs-on: ubuntu-latest
    outputs:
      configuration: ${{ github.ref == 'refs/heads/main' && 'Release' || 'Debug' }}
      webui-config: ${{ github.ref == 'refs/heads/main' && '' || 'development' }}
      environment: ${{ github.ref == 'refs/heads/main' && 'Production' || 'Development' }}
    steps:
      - name: Empty Step
        run: |
          echo "null"

  build:
    name: Build Batch Processing API
    needs: [setup-env]
    uses: ./.github/workflows/_batchprocessing.api.ci.yml
    with:
      configuration: ${{ needs.setup-env.outputs.configuration }}
      webui-configuration: ${{ needs.setup-env.outputs.webui-config }}
      artifactName: batch-processing-api
    secrets: inherit

  prod-deploy:
    name: Deploy to Production
    needs: [setup-env, build]
    uses: ./.github/workflows/_batchprocessing.api.cd.yml
    permissions:
      id-token: write
      contents: read
    with:
      environment: ${{ needs.setup-env.outputs.environment }}
      ref: ${{ github.sha }}
      artifactName: batch-processing-api
      serviceName: batch-processing-api
    secrets: inherit
