name: Build & Deploy Order Echo Serverless Function

on:
  push:
    branches:
      - main
      - 'release/**'
      - development
    paths:
      - 'src/Serverless/OrderEcho/**'
  workflow_dispatch:

jobs:
  # Setup variables for use by subsequent jobs
  setup-env:
    name: Setup Environment Variables
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ github.ref == 'refs/heads/main' && '["Demo", "Production"]' || startsWith(github.ref, 'refs/heads/release') && '["Test"]' || '["Development"]' }}
      artifactName: 'order-echo-serverless'
    steps:
      - name: Empty Step
        run: |
          echo "null"

  build:
    name: Build Order Echo Serverless Function
    needs: [setup-env]
    uses: ./.github/workflows/_orderecho.serverless.ci.yml
    with:
      artifactName: ${{ needs.setup-env.outputs.artifactName }}
    secrets: inherit

  deploy:
    name: Deploy Order Echo Serverless Function
    needs: [setup-env, build]
    uses: ./.github/workflows/_cloudrun.gcp.cd.yml
    permissions:
      id-token: write
      contents: read
    strategy:
      matrix:
        environment: ${{ fromJSON(needs.setup-env.outputs.environment) }}
    with:
      environment: ${{ matrix.environment }}
      ref: ${{ github.sha }}
      artifactName: ${{ needs.setup-env.outputs.artifactName }}
      serviceName: order-echo
      cloudRunEnvVars: '["SIGNATURE_TYPE=cloudevent", "ENTRY_POINT=subscribe"]'
    secrets: inherit
